

build:
	gcc -Wall -Wextra ninel.c -o ninel
	gcc -Wall -Wextra vectsecv.c -o vectsecv
	gcc -Wall -Wextra codeinvim.c -o codeinvim
	gcc -Wall -Wextra nomogram.c -o nomogram

clean:
	rm -rf ninel vectsevc codeinvim nomogram